name:  CI Process
run-name:  ${{ github.actor}} is learning Github Actions
on:  [push]
jobs:
  behave-testing:
    #Setup of simple OS of choice. i.e. Linux
    #create VM with ubuntu OS
    runs-on:  ubuntu-latest

    steps:
      #Setup of envirionment for test
      - name:  checkout
        uses:  actions/checkout@v4.2.2
      - name:  List repo
        run:  |
            ls
            
      #install python
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version:  '3.9'

      #install behave
      - name:  install pip
        run:  |
          python -m pip install --upgrade pip
          pip install behave

      #run
      - name:  run behave test
        run:  |
          behave

      - name: Create Issues
        uses:  jayalfredprufrock/create-issues-action@v1.2.1
        with:
            template-path: .github/issues/**/*.md
            labels: "automation,task"
            assignees: "your-username"
            github-token: ${{ secrets.GITHUB_TOKEN }}
