name:  CI Process
run-name:  ${{ github.actor}} is learning Github Actions
on:  [push]
jobs:
  behave-testing:
    #Setup of simple OS of choice. i.e. Linux
    #create VM with ubuntu OS
    runs-on:  ubuntu-latest

    steps:
      #Setup of envirionment for test
      - name:  checkout
        uses:  actions/checkout@v4.2.2
      - name:  List repo
        run:  |
            ls
          
      - name:  Install Python package
        uses:  durandtibo/pip-install-package-action@v0.3.1
        with:  
          package-name:  behave
          package-version:  '1.2.6'
          python-version:  '3.9'

      - name:  Run Behave test
        run:  |
          behave
          
      #install pip
      - name: pip-install-package
        uses: durandtibo/pip-install-package-action@v0.3.1
        with:
          # The package name
          package-name: requests
          # The package target version
          package-version: 2.28.1
          # The python version
          python-version: 3.9
      
                
