name: CI Process
run-name: ${{ github.actor}} is learning Github Actions
on: [push]
jobs:
  behave-testing:
    #Setup of simple OS of choice. i.e. Linux
    #create VM with ubuntu OS
    runs-on:ubuntu-latest

    steps:
      #Setup of envirionment for test
      - name: checkout
        uses: actions/checkout@v4.2.2
      -name: List repo
        run: |
          ls
